name: example
version: 1.0.0
publish_to: none
description: >
  Just an example, not for publishing.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  data_class:
    git:
      url: git://github.com/Supernova-Studio/builder_generator_dart.git
      ref: feature/hierarchy-changes
      path: data_class/

  json_annotation: ^3.0.1
  built_collection: ^4.3.2

dev_dependencies:
  build_runner: ^1.10.12

  data_class_generator:
    path: ../data_class_generator
#    git:
#      url: git://github.com/Supernova-Studio/builder_generator_dart.git
#      path: data_class_generator/

  test: ^1.15.1

  json_serializable: ^3.5.1

