name: example
version: 1.0.0
publish_to: none
description: >
  Just an example, not for publishing.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_value_custom:
    path: ../built_value_custom

  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.10.0

  built_value_generator_custom:
    path: ../built_value_generator_custom

  test: ^1.15.1
  json_serializable: ^3.3.0
