name: data_class_generator
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.0
  source_gen: ^0.9.0
  quiver: '>=0.21.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
  build_test: ^1.0.0
  build_runner: ^1.0.0
  logging: ^0.11.0
  pedantic: ^1.4.0

  built_value_generator: ^7.0.0