name: data_class_generator
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.0
  source_gen: ^0.9.0
  quiver: '>=0.21.0 <3.0.0'

  data_class:
    #    path: ../data_class
    git:
      url: git://github.com/Supernova-Studio/builder_generator_dart.git
      ref: feature/hierarchy-changes
      path: data_class/

dev_dependencies:
  test: ^1.0.0
  build_test: ^1.0.0
  build_runner: ^1.0.0
  logging: ^0.11.0
  pedantic: ^1.4.0

#  built_value_generator: ^7.1.0
