name: built_value_custom
version: 7.1.0
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the runtime dependency.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  collection: ^1.14.13
  fixnum: ^0.10.0
  quiver: '>=0.21.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.4.0
  test: ^1.0.0
